apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.topology.filter.name }}
  labels:
    helm.sh/chart: {{ include "moira.chart" . }}
    app.kubernetes.io/name: {{ .Values.topology.filter.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - name: graphite
      port: 2003
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.topology.filter.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP